name: WakaTime Readme
on:
  schedule:
    # Runs at 12am UTC daily
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          # This text will be injected into your README automatically
          # You don't need a specific placeholder, it appends to the end 
          # or looks for if you configure it.